### ISSUE TITLE
About the gt file

### ISSUE THREAD

**Issue by 213pk** [Aaron-Pu/PEL4VAD#2]
If I want to perform your method using my custom dataset, how to generate the ground truth .npy file? Thanks!

**Comment by Aaron-Pu** [comment]
For the test videos, you can generate the ground-truth using the following code:
```
import os
import numpy as np
import cv2

label_file = '.../annotations.list'
video_root = '.../video_file'
gt_list = list(open(label_file))
for idx in range(len(gt_list)):
    video_name = gt_list[idx].strip('\n').split(' ')[0]
    video_label = gt_list[idx].strip('\n').split(' ')[1:]
    cap = cv2.VideoCapture(os.path.join(video_root, video_name))
    frames = int(cap.get(7))
    video_gt = np.zeros(frames)
    for i in range(len(video_label)//2):
        s_idx = int(video_label[2*i])
        e_idx = int(video_label[2*i + 1])
        video_gt[s_idx - 1: e_idx] = 1.
    np.save('.../'+video_name[:-4]+'.npy', video_gt)
```


Please make sure that the annotations.list is organized as follows:
```
abnormal_001.mp4 3 8  # start1 end1
abnormal_002.mp4 16 64 247 459  # start1 end1 start2 end2
...
```

Hope this helps!

**Comment by 213pk** [comment]
Thanks for your code. For the annotation "abnormal_001.mp4 3 8", do "3" and "8" mean the frame number?

**Comment by Aaron-Pu** [comment]
That's correct. The two numbers indicate the start and end frame of a video.


Best,
Yujiang

---- Replied Message ----
From 213pk ***@***.***> Date 08/03/2023 15:57 To Aaron-Pu/PEL4VAD ***@***.***> Cc Yujiang ***@***.***>,
Comment ***@***.***> Subject Re: [Aaron-Pu/PEL4VAD] About the gt file (Issue #2)  

Thanks for your code. For the annotation "abnormal_001.mp4 3 8", do "3" and "8" mean the frame number?

**Comment by 213pk** [comment]
Thanks! I used the provided feature extraction link to extract the features using I3D. The link is https://iashin.ai/video_features/models/i3d/. The input video name is "Fighting_temp02.avi" (my custom video). And I generated four .npy files. They are named "Fighting_temp02_flow.npy", "Fighting_temp02_fps.npy", "Fighting_temp02_rgb.npy", and "Fighting_temp02_timestamps_ms.npy", respectively. Should I use all of them as the features?

**Comment by Aaron-Pu** [comment]
No. Only the flow.npy and rgb.npy files are video features, and our model adopts rgb.npy as input.
Best,
Yujiang​

---- Replied Message ----
From 213pk ***@***.***> Date 08/03/2023 18:04 To Aaron-Pu/PEL4VAD ***@***.***> Cc Yujiang ***@***.***>,
Comment ***@***.***> Subject Re: [Aaron-Pu/PEL4VAD] About the gt file (Issue #2)  

Thanks! I used the provided feature extraction link to extract the features using I3D. The link is https://iashin.ai/video_features/models/i3d/. The input video name is "Fighting_temp02.avi" (my custom video). And I generated four .npy files. They are named "Fighting_temp02_flow.npy", "Fighting_temp02_fps.npy", "Fighting_temp02_rgb.npy", and "Fighting_temp02_timestamps_ms.npy", respectively. Should I use all of them as the features?

**Comment by 213pk** [comment]
Thanks! I have tried your method to generate the gt file of one video. And I also extract the features of this video. The anomaly of the video is fighting. So I also change the abn_label file. I want to use the trained sh model to test this video. But the errors occur:

Traceback (most recent call last):
  File "main.py", line 137, in <module>
    main(cfg)
  File "main.py", line 125, in main
    infer_func(model, test_loader, gt, logger, cfg)
  File "/media/wxy/a9d6363f-a285-47d6-acb5-51f99e9c13f7/home/wxy/PEL4VAD-master/infer.py", line 16, in infer_func
    for i, (v_input, name) in enumerate(dataloader):
  File "/home/wxy/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/wxy/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/wxy/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wxy/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/wxy/a9d6363f-a285-47d6-acb5-51f99e9c13f7/home/wxy/PEL4VAD-master/dataset.py", line 140, in __getitem__
    v_feat = np.array(np.load(video_path), dtype=np.float32)
  File "/home/wxy/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
IsADirectoryError: [Errno 21] Is a directory: './'

How to solve it? Thanks!

**Comment by Aaron-Pu** [comment]
We used 10-crop data augmentation during the testing phase. If you have only one feature as input, try modifying the test batch size in config.py to 1.

**Comment by 213pk** [comment]
I have tried to set test bs to 1 but still the same problem. Could you provide the link or other information of 10-crop data augmentation? Thanks!!!
